language: rust

before_install:
  - sudo apt-get -y install libglu1-mesa

# grab the gmsh SDK
before_script:
  - wget http://gmsh.info/bin/Linux/gmsh-4.4.1-Linux64-sdk.tgz -O /tmp/gmsh-sdk.tar.gz
  - tar -xvf /tmp/gmsh-sdk.tar.gz
  - export GMSH_LIB_DIR=$PWD/gmsh-4.4.1-Linux64-sdk/lib/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/gmsh-4.4.1-Linux64-sdk/lib/

cache: cargo

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
